### PR TITLE
#106 allow TODO and TODO: tags for pdd puzzles

### LINKED ISSUE #106: Allow `TODO:` and `TODO` as PDD tag to better align with C#/F# .NET Codebases
For .NET Developers, they don't use annotations and the convention is to write TODO in all caps, sometimes with a : at the end.

It would be a very useful feature if 0pdd were able to treat those as Puzzle tags and the interpret the remainder of the puzzle to create a ticket.

This was one of the reasons I stopped using 0pdd in some of my .NET projects. It was very inconsistent from the normal code style.

Example: ```// TODO: #16 This needs to use Trigonometry to apply the velocity correctly```

Original ticket: https://github.com/yegor256/0pdd/issues/202

### PR DESCRIPTION
**Pull request by a6cexz**
Added TODO and TODO: tags support for pdd puzzles

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#109](https://github.com/yegor256/pdd/issues/109) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#109](https://github.com/yegor256/pdd/issues/109); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#109](https://github.com/yegor256/pdd/issues/109); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#109` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#109](https://github.com/yegor256/pdd/issues/109) is now out of scope

**Pull request merged**
