### PR TITLE
fix #104 Garbage characters in a puzzle name with Thymeleaf parser-le…

### LINKED ISSUE #104: Garbage characters in a puzzle name with Thymeleaf parser-level comment
For the following comment:
```html
<!--/* @todo #884 /collection/{slug}/estimation: optimize summing of prices */-->
```
@0pdd created the issue with a title `/collection/{slug}/estimation: optimize summing of prices */-->`.

I think that it has happened because pdd incorrectly parses [Thymeleaf parser-level comments](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#thymeleaf-parser-level-comment-blocks).

Expected result: puzzle shouldn't have `*/-->` at the end.

### PR DESCRIPTION
**Pull request by a6cexz**
Stip thymeleaf comment closing tag from puzzle body

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#110](https://github.com/yegor256/pdd/issues/110) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#110](https://github.com/yegor256/pdd/issues/110); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#110` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#110](https://github.com/yegor256/pdd/issues/110) is now out of scope

**Pull request merged**
