### PR TITLE
#85 Skip invalid emails.

### PR DESCRIPTION
**Pull request by rok-povsic**
As per #85

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#91](https://github.com/yegor256/pdd/issues/91) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#91](https://github.com/yegor256/pdd/issues/91) is now out of scope

**Pull request merged**
