### PR TITLE
#121 Fix the ruby version in the travis build.

### LINKED ISSUE #121: Build of the project is broken.
Found in #120. 

For now, a build of the whole project is broken (see this: https://travis-ci.org/yegor256/pdd/builds/556113316?utm_source=github_status&utm_medium=notification).

I suppose that we need to update the ruby version.

### PR DESCRIPTION
**Pull request by aivinog1**
This fixes #121. I've chosen the minimal version that the build is passed.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#122` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
