### PR TITLE
#123 Update the ruby version and fix rubocop errors

### LINKED ISSUE #123: Update ruby version to 2.3
After #122. Seem to be that the lowest ruby version of the project became 2.3. It needs to change it in the following files:

- [x] https://github.com/yegor256/pdd/blob/master/pdd.gemspec
- [x] https://github.com/yegor256/pdd/blob/master/.rubocop.yml
- [x] https://github.com/yegor256/pdd/blob/master/appveyor.yml

And maybe in other files.

### PR DESCRIPTION
**Pull request by aivinog1**
This is a fix for #123. I've updated a Ruby version and fixed some errors.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#130](https://github.com/yegor256/pdd/issues/130) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#130](https://github.com/yegor256/pdd/issues/130); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#130` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#130](https://github.com/yegor256/pdd/issues/130) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
