### PR TITLE
#119 Enable the rubocop on bin/ and fix its errors

### LINKED ISSUE #119: Bin directory from rubocop is excluded
See this: https://github.com/yegor256/pdd/blob/48cd3ba95a258e438ed9a0e5b0a37de71fdde57f/.rubocop.yml#L3

The bin folder must be checked by the Rubocop.

### PR DESCRIPTION
**Pull request by aivinog1**
This fixes #119. I've enabled the rubocop on the bin dir and fixed some of its errors.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#127` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
