### PR TITLE
#126 Start using aruba to test stderr.

### LINKED ISSUE #126: rake.feature:11-13: For now, there haven't a proper...
The puzzle `114-89012c92` from #114 has to be resolved: 

https://github.com/yegor256/pdd/blob/5a9c16ff2c130e1efc5fefee31b91437b29b9a91/features/rake.feature#L11-L13

The puzzle was created by Alexey Vinogradov on 09-Jul-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by aivinog1**
This is a fix to #126. I've tried to use Aruba to catch stderr.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#129](https://github.com/yegor256/pdd/issues/129) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#129](https://github.com/yegor256/pdd/issues/129); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by aivinog1** [comment]
@yegor256 I've fixed my puzzle message, can you try to merge again, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by aivinog1** [comment]
@yegor256 I've fixed my failing test. Can you merge this again, please?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#129](https://github.com/yegor256/pdd/issues/129); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#129` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#129](https://github.com/yegor256/pdd/issues/129) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
