### PR TITLE
#114 Add the new Rake task without implementation

### LINKED ISSUE #114: Rake task
Let's create a rake task

You may see how Rake task is implemented in this repo: [yegor256/xcop](https://github.com/yegor256/xcop)

### PR DESCRIPTION
**Pull request by aivinog1**
This fixes #114. I've added a skeleton without implementation but with PDD todos.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#120](https://github.com/yegor256/pdd/issues/120) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#120](https://github.com/yegor256/pdd/issues/120); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#120` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#120](https://github.com/yegor256/pdd/issues/120) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
